//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class workon
    {
        public int pid { get; set; }
        public int empID { get; set; }
        public Nullable<int> hours { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual project project { get; set; }
        public virtual project project1 { get; set; }
    }
}
